spring:
  application:
    name: PlanningPoker
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URLjdbc:jdbc:postgresql://localhost:5432/dev}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  flyway:
    default-schema: planning_poker

server:
  port: 8080
